import { Category } from '../types/expense';
import { translateToEnglish } from './translateToEnglish';

// Ordered so a description matching more than one list picks the earlier,
// more specific category — e.g. "grocery store" hits Groceries before the
// generic "store" keyword under Shopping ever gets a chance to match. Each
// entry is an individually curated word or short phrase that plausibly
// appears verbatim in a real expense description (dish names, venue types,
// well-known brand/chain names, gear, fees, etc.) — no generated filler.

const CATEGORY_KEYWORDS: [Category, string[]][] = [
  [
    'Food',
    [
      'restaurant', 'food', 'lunch', 'dinner', 'breakfast', 'brunch', 'coffee', 'cafe', 'meal',
      'snack', 'pizza', 'burger', 'sushi', 'bar', 'drinks', 'bakery', 'diner', 'eat', 'noodle',
      'sandwich', 'taco', 'buffet', 'supper', 'feast', 'potluck', 'picnic', 'banquet',
      'tasting menu', 'happy hour', 'late night snack', 'midnight snack', 'second breakfast',
      'high tea', 'afternoon tea', 'tea time', 'aperitif', 'nightcap', 'tasting', 'food tour',
      'street food tour', 'dinner date', 'lunch break', 'coffee break', 'eatery', 'bistro',
      'trattoria', 'brasserie', 'canteen', 'food court', 'food truck', 'drive-thru', 'takeout',
      'delivery', 'catering', 'tavern', 'pub', 'gastropub', 'steakhouse', 'seafood restaurant',
      'sushi bar', 'ramen shop', 'noodle bar', 'pizzeria', 'patisserie', 'confectionery', 'deli',
      'delicatessen', 'grill', 'bbq joint', 'smokehouse', 'chophouse', 'brewery', 'winery',
      'vineyard', 'distillery', 'cocktail bar', 'wine bar', 'beer garden', 'rooftop bar',
      'speakeasy', 'juice bar', 'smoothie bar', 'coffee shop', 'coffeehouse', 'tea house',
      'dessert shop', 'ice cream parlor', 'gelateria', 'creamery', 'food stall', 'market stall',
      'food kiosk', 'concession stand', 'snack bar', 'buffet restaurant', 'all you can eat',
      'fine dining', 'fast food', 'casual dining', 'brunch spot', 'pop up restaurant',
      'italian restaurant', 'chinese restaurant', 'japanese restaurant', 'mexican restaurant',
      'indian restaurant', 'thai restaurant', 'french restaurant', 'greek restaurant',
      'spanish restaurant', 'korean restaurant', 'vietnamese restaurant', 'lebanese restaurant',
      'turkish restaurant', 'mediterranean restaurant', 'seafood shack', 'tapas bar',
      'dim sum restaurant', 'burrito', 'quesadilla', 'enchilada', 'fajita', 'nachos', 'pasta',
      'spaghetti', 'lasagna', 'risotto', 'paella', 'curry', 'biryani', 'kebab', 'falafel',
      'hummus', 'shawarma', 'gyro', 'souvlaki', 'dumpling', 'dim sum', 'ramen', 'udon', 'soba',
      'pho', 'banh mi', 'pad thai', 'tom yum', 'sashimi', 'tempura', 'teriyaki', 'bibimbap',
      'bulgogi', 'kimchi', 'croissant', 'baguette', 'crepe', 'quiche', 'fondue', 'schnitzel',
      'bratwurst', 'goulash', 'pierogi', 'borscht', 'waffle', 'pancake', 'omelette', 'frittata',
      'salad', 'soup', 'stew', 'chili', 'wings', 'ribs', 'steak', 'roast', 'casserole', 'pie',
      'tart', 'cake', 'cookie', 'brownie', 'donut', 'muffin', 'bagel', 'pretzel', 'popcorn',
      'fries', 'chips', 'hotdog', 'sub', 'wrap', 'panini', 'focaccia', 'ciabatta', 'gelato',
      'sorbet', 'ice cream', 'sundae', 'milkshake', 'churro', 'empanada', 'tamale', 'ceviche',
      'poutine', 'haggis', 'tapas', 'antipasto', 'carpaccio', 'bruschetta', 'calzone',
      'stromboli', 'gnocchi', 'ravioli', 'tortellini', 'cannoli', 'tiramisu', 'baklava',
      'macaron', 'eclair', 'souffle', 'creme brulee', 'flan', 'custard', 'pudding', 'porridge',
      'oatmeal', 'granola', 'cereal', 'toast', 'bacon', 'sausage', 'hash browns', 'french toast',
      'bagel and lox', 'pork belly', 'brisket', 'pulled pork', 'meatball', 'meatloaf',
      'shepherds pie', 'fish and chips', 'clam chowder', 'lobster roll', 'crab cake', 'oyster',
      'shrimp cocktail', 'calamari', 'escargot', 'foie gras', 'charcuterie', 'cheese board',
      'onion rings', 'spring roll', 'egg roll', 'potsticker', 'wonton', 'satay', 'laksa',
      'congee', 'kimbap', 'tteokbokki', 'japchae', 'okonomiyaki', 'takoyaki', 'yakitori',
      'donburi', 'katsu', 'curry rice', 'naan', 'roti', 'paratha', 'samosa', 'pakora',
      'tikka masala', 'vindaloo', 'korma', 'dal', 'chana masala', 'tandoori', 'moussaka',
      'spanakopita', 'dolma', 'tabbouleh', 'baba ganoush', 'pita', 'injera', 'jollof rice',
      'fufu', 'pupusa', 'arepa', 'mole sauce', 'churrasco', 'feijoada', 'asado', 'chimichurri',
      'tostones', 'espresso', 'latte', 'cappuccino', 'macchiato', 'americano', 'mocha',
      'cortado', 'flat white', 'iced coffee', 'cold brew', 'tea', 'chai', 'matcha', 'green tea',
      'black tea', 'herbal tea', 'bubble tea', 'boba', 'hot chocolate', 'juice', 'orange juice',
      'smoothie', 'milkshake drink', 'soda', 'cola', 'lemonade', 'sparkling water',
      'mineral water', 'wine', 'red wine', 'white wine', 'rose wine', 'champagne', 'prosecco',
      'beer', 'lager', 'ale', 'stout', 'ipa', 'cider', 'cocktail', 'mojito', 'margarita',
      'martini', 'mai tai', 'pina colada', 'sangria', 'whiskey', 'bourbon', 'scotch', 'vodka',
      'rum', 'gin', 'tequila', 'sake', 'soju', 'brandy', 'liqueur', 'digestif', 'spritz',
      'negroni', 'daiquiri', 'old fashioned', 'bloody mary', 'mimosa', 'bellini', 'shot glass',
      'craft beer', 'microbrew', 'eating', 'dine', 'dining', 'hungry', 'thirsty', 'order food',
      'reservation', 'tip', 'waiter', 'waitress', 'server', 'chef', 'cook', 'menu', 'appetizer',
      'entree', 'main course', 'side dish', 'dessert', 'course', 'portion', 'recipe',
      'ingredient', 'spice', 'seasoning', 'sauce', 'gravy', 'dressing', 'topping', 'garnish',
      'leftover', 'doggy bag', 'to go', 'carryout', 'room service', 'minibar', 'vending machine',
      'gas station food', 'convenience meal', 'meal prep', 'meal deal', 'combo meal',
      'kids meal', 'set menu', 'chefs special', 'daily special', 'prix fixe',
      'all inclusive meal', 'meal plan', 'food voucher',
    ],
  ],
  [
    'Groceries',
    [
      'grocery', 'groceries', 'supermarket', 'convenience store', 'pharmacy', 'drugstore',
      'hypermarket', 'grocery store', 'grocer', 'corner store', 'mini mart', 'general store',
      'farmers market', 'food market', 'wholesale club', 'discount grocer', 'organic market',
      'health food store', 'butcher shop', 'fishmonger', 'greengrocer', 'bodega',
      'co-op grocery', 'chemist', 'apothecary', 'health store', 'vitamin shop', 'big box store',
      'warehouse store', 'apple', 'banana', 'orange fruit', 'grape', 'strawberry', 'blueberry',
      'raspberry', 'blackberry', 'watermelon', 'cantaloupe', 'pineapple', 'mango', 'papaya',
      'kiwi', 'peach', 'plum', 'pear', 'cherry', 'apricot', 'lemon', 'lime fruit', 'grapefruit',
      'pomegranate', 'fig', 'date fruit', 'coconut', 'avocado', 'tomato', 'cucumber', 'lettuce',
      'spinach', 'kale', 'cabbage', 'broccoli', 'cauliflower', 'carrot', 'potato',
      'sweet potato', 'onion', 'garlic', 'ginger', 'bell pepper', 'chili pepper', 'zucchini',
      'squash', 'pumpkin', 'eggplant', 'mushroom', 'corn', 'peas', 'green beans', 'asparagus',
      'celery', 'radish', 'beet', 'turnip', 'artichoke', 'leek', 'scallion', 'fresh herbs',
      'basil', 'cilantro', 'parsley', 'mint leaves', 'dill', 'rosemary', 'thyme', 'milk',
      'cheese', 'yogurt', 'butter', 'cream', 'sour cream', 'cottage cheese', 'cream cheese',
      'mozzarella', 'cheddar', 'parmesan', 'feta', 'brie', 'gouda', 'buttermilk', 'ghee',
      'margarine', 'whipped cream', 'egg carton', 'bread', 'rice', 'pasta noodles', 'flour',
      'sugar', 'table salt', 'cooking oil', 'olive oil', 'vinegar', 'breakfast cereal', 'oats',
      'granola bar', 'honey', 'jam', 'peanut butter', 'nutella', 'crackers', 'potato chips',
      'cookies', 'canned beans', 'canned tomatoes', 'canned soup', 'broth', 'stock cube',
      'spice jar', 'seasoning mix', 'ketchup', 'mustard', 'mayonnaise', 'soy sauce', 'hot sauce',
      'salad dressing', 'baking soda', 'baking powder', 'yeast', 'cornstarch', 'cocoa powder',
      'chocolate bar', 'candy', 'chewing gum', 'snack bar', 'protein bar', 'trail mix',
      'almonds', 'cashews', 'peanuts', 'walnuts', 'raisins', 'dried fruit', 'organic produce',
      'gluten free bread', 'whole grain bread', 'raw chicken', 'raw beef', 'raw pork',
      'lamb meat', 'turkey meat', 'sliced bacon', 'sausage links', 'sliced ham', 'salami',
      'fish fillet', 'salmon fillet', 'canned tuna', 'frozen shrimp', 'crab meat', 'ground beef',
      'steak cut', 'deli meat', 'frozen pizza', 'frozen vegetables', 'frozen fruit',
      'bag of ice', 'frozen meal', 'tv dinner', 'juice box', 'soda pack', 'bottled water pack',
      'sparkling water pack', 'energy drink', 'sports drink', 'beer pack', 'bottle of wine',
      'paper towel', 'toilet paper', 'facial tissue', 'napkin', 'dish soap', 'laundry detergent',
      'fabric softener', 'cleaning spray', 'bleach', 'kitchen sponge', 'trash bag',
      'aluminum foil', 'plastic wrap', 'ziploc bag', 'batteries', 'light bulb', 'air freshener',
      'dishwasher tablet', 'shampoo', 'conditioner', 'bar soap', 'body wash', 'toothpaste',
      'toothbrush', 'deodorant', 'razor', 'shaving cream', 'body lotion', 'sunscreen',
      'cotton swab', 'cotton ball', 'feminine care', 'diaper', 'baby wipe', 'baby formula',
      'vitamin supplement', 'pain reliever', 'aspirin', 'ibuprofen', 'cold medicine',
      'allergy medicine', 'bandage', 'first aid kit', 'hand sanitizer', 'face mask',
      'contact lens solution', 'dog food', 'cat food', 'pet treat', 'cat litter', 'pet toy',
    ],
  ],
  [
    'Lodging',
    [
      'hotel', 'hostel', 'airbnb', 'motel', 'resort', 'lodging', 'accommodation', 'guesthouse',
      'check-in', 'check in', 'room booking', 'boutique hotel', 'luxury hotel', 'budget hotel',
      'business hotel', 'airport hotel', 'beach resort', 'all inclusive resort', 'spa resort',
      'ski resort', 'eco lodge', 'bed and breakfast', 'b&b stay', 'country inn', 'chalet',
      'cabin rental', 'cottage rental', 'villa rental', 'bungalow', 'apartment rental',
      'vacation rental', 'serviced apartment', 'extended stay hotel', 'capsule hotel',
      'love hotel', 'ryokan', 'onsen stay', 'glamping', 'campsite', 'campground', 'rv park',
      'caravan park', 'youth hostel', 'backpacker hostel', 'dormitory room', 'mountain hut',
      'farmstay', 'homestay', 'guest room', 'private room', 'shared room', 'dorm bed',
      'penthouse suite', 'honeymoon suite', 'presidential suite', 'junior suite',
      'standard room', 'deluxe room', 'executive room', 'family room', 'twin room',
      'double room', 'single room', 'suite upgrade', 'reception desk', 'front desk', 'concierge',
      'housekeeping', 'room service', 'minibar', 'turndown service', 'late checkout',
      'early check-in', 'checkout', 'key card', 'room key', 'bellhop', 'porter', 'valet parking',
      'hotel lobby', 'hotel bar', 'hotel restaurant', 'hotel spa', 'hotel gym', 'hotel pool',
      'rooftop pool', 'sauna', 'jacuzzi', 'hot tub', 'balcony room', 'ocean view room',
      'city view room', 'garden view room', 'non smoking room', 'smoking room', 'adjoining room',
      'connecting room', 'wifi fee', 'resort fee', 'cleaning fee', 'cancellation fee',
      'booking fee', 'security deposit', 'nightly rate', 'room rate', 'reservation confirmation',
      'booking confirmation', 'travel itinerary', 'stay voucher', 'booking.com', 'expedia',
      'hotels.com', 'agoda', 'tripadvisor booking', 'vrbo', 'homeaway', 'couchsurfing',
      'hostelworld', 'trivago', 'hilton', 'marriott', 'hyatt', 'holiday inn', 'sheraton',
      'westin', 'ritz carlton', 'four seasons', 'intercontinental', 'radisson', 'novotel',
      'ibis', 'mercure', 'accor', 'wyndham', 'comfort inn', 'days inn', 'super 8', 'motel 6',
      'la quinta', 'red roof inn', 'hampton inn', 'doubletree', 'embassy suites', 'courtyard',
      'residence inn', 'fairfield inn', 'springhill suites', 'aloft', 'kimpton', 'st regis',
      'conrad', 'waldorf astoria', 'le meridien', 'sonesta', 'omni hotels', 'fairmont',
      'shangri-la', 'peninsula hotel', 'mandarin oriental', 'rosewood hotel', 'aman resorts',
      'six senses', 'banyan tree', 'club med', 'generator hostels', 'oyo rooms',
    ],
  ],
  [
    'Transport',
    [
      'taxi', 'uber', 'lyft', 'bus', 'train', 'metro', 'subway', 'flight', 'airline', 'airport',
      'car rental', 'rental car', 'gas', 'fuel', 'parking', 'ferry', 'toll', 'ride', 'transit',
      'tram', 'car', 'suv', 'sedan', 'minivan', 'cargo van', 'pickup truck', 'motorcycle',
      'scooter rental', 'moped', 'bicycle', 'bike rental', 'e-bike', 'electric scooter',
      'limousine', 'limo', 'shuttle bus', 'coach bus', 'charter bus', 'double decker bus',
      'school bus', 'minibus', 'carpool', 'rideshare', 'car sharing', 'zipcar', 'bus stop',
      'bus station', 'train station', 'subway station', 'metro station', 'platform',
      'boarding pass', 'departure gate', 'baggage claim', 'check-in counter', 'security line',
      'customs', 'immigration', 'layover', 'connecting flight', 'direct flight',
      'one way ticket', 'round trip ticket', 'business class', 'economy class', 'first class',
      'seat upgrade', 'train ticket', 'rail pass', 'metro card', 'transit pass', 'bus pass',
      'monthly pass', 'day pass', 'fare', 'toll road', 'toll booth', 'highway', 'expressway',
      'motorway', 'interstate', 'road trip', 'carpool lane', 'parking garage', 'parking lot',
      'parking meter', 'valet parking service', 'car wash', 'oil change', 'tire shop',
      'drivers license', 'car registration', 'car insurance', 'delta airlines',
      'united airlines', 'american airlines', 'southwest airlines', 'jetblue', 'spirit airlines',
      'frontier airlines', 'alaska airlines', 'air canada', 'british airways', 'lufthansa',
      'air france', 'klm', 'emirates airline', 'qatar airways', 'etihad airways',
      'turkish airlines', 'singapore airlines', 'cathay pacific', 'japan airlines',
      'ana airlines', 'korean air', 'china eastern', 'china southern', 'air china', 'ryanair',
      'easyjet', 'wizz air', 'vueling', 'norwegian air', 'iberia', 'tap portugal', 'swiss air',
      'austrian airlines', 'finnair', 'sas scandinavian', 'aeroflot', 'el al', 'royal jordanian',
      'egyptair', 'kenya airways', 'south african airways', 'qantas', 'air new zealand',
      'virgin atlantic', 'virgin australia', 'copa airlines', 'avianca', 'latam airlines',
      'aeromexico', 'gol airlines', 'azul airlines', 'hertz', 'avis', 'enterprise rent a car',
      'budget rental car', 'alamo rental', 'national car rental', 'sixt', 'europcar',
      'thrifty car rental', 'dollar rental', 'zipcar rental', 'grab ride', 'didi ride',
      'bolt ride', 'gojek', 'ola cabs', 'careem', 'free now', 'curb taxi', 'subway system',
      'the underground', 'tube london', 'light rail', 'commuter rail', 'regional train',
      'bullet train', 'high speed rail', 'tram line', 'streetcar', 'monorail', 'cable car',
      'funicular', 'gondola lift', 'ski lift transport', 'amtrak', 'eurostar', 'thalys',
      'tgv train', 'deutsche bahn', 'shinkansen', 'renfe', 'trenitalia', 'sncf', 'via rail',
      'greyhound bus', 'megabus', 'flixbus', 'national express bus', 'citi bike', 'lime scooter',
      'bird scooter', 'santander cycles', 'ferry ticket', 'ferry crossing', 'water taxi',
      'boat ride', 'cruise ship', 'cruise line', 'cruise cabin', 'cruise excursion',
      'harbor fee', 'dock fee', 'pier', 'port fee', 'gas station', 'fuel station', 'petrol',
      'diesel', 'electric charging', 'ev charger', 'charging station', 'shell station',
      'chevron station', 'bp station', 'exxon station', 'mobil station', 'texaco station',
    ],
  ],
  [
    'Activities',
    [
      'ticket', 'tour', 'museum', 'excursion', 'activity', 'attraction', 'hike', 'safari',
      'cruise', 'admission', 'zoo', 'aquarium', 'guide', 'rental gear', 'diving', 'skiing',
      'hiking', 'trekking', 'climbing', 'rock climbing', 'bouldering', 'mountaineering',
      'camping trip', 'kayaking', 'canoeing', 'rafting', 'white water rafting', 'paddleboarding',
      'surfing lesson', 'windsurfing', 'kitesurfing', 'snorkeling', 'scuba diving',
      'free diving', 'sailing trip', 'boating', 'fishing trip', 'jet ski rental', 'parasailing',
      'zip lining', 'bungee jumping', 'skydiving', 'paragliding', 'hang gliding',
      'hot air balloon ride', 'horseback riding', 'biking tour', 'cycling tour',
      'mountain biking', 'atv tour', 'segway tour', 'walking tour', 'food tasting tour',
      'wine tour', 'brewery tour', 'city tour', 'bus tour activity', 'helicopter tour',
      'private tour', 'group tour', 'guided tour', 'self guided tour', 'audio guide rental',
      'day trip excursion', 'excursion package', 'snowboarding', 'cross country skiing',
      'ski lesson', 'ski pass', 'ski rental', 'snowmobiling', 'ice skating', 'sledding',
      'tobogganing', 'snowshoeing', 'ski lift ticket', 'art gallery', 'science museum',
      'history museum', 'natural history museum', 'planetarium', 'observatory', 'safari park',
      'wildlife reserve', 'national park', 'state park', 'botanical garden', 'arboretum',
      'theme park', 'amusement park', 'water park', 'adventure park', 'escape room',
      'haunted house', 'castle tour', 'palace tour', 'cathedral visit', 'church visit',
      'temple visit', 'mosque visit', 'synagogue visit', 'monastery visit', 'monument visit',
      'memorial visit', 'landmark visit', 'historic site', 'archaeological site',
      'ancient ruins', 'fortress tour', 'citadel tour', 'tower visit', 'bridge attraction',
      'lighthouse visit', 'viewpoint', 'lookout point', 'scenic overlook', 'cave tour',
      'canyon tour', 'waterfall visit', 'hot spring visit', 'volcano tour', 'glacier tour',
      'island hopping', 'beach day activity', 'spa day activity', 'yoga retreat',
      'wellness retreat', 'meditation retreat', 'admission fee', 'entry fee', 'ticket price',
      'entrance ticket', 'skip the line ticket', 'fast pass', 'express pass', 'combo ticket',
      'annual pass', 'season pass', 'membership pass', 'student discount ticket', 'child ticket',
      'adult ticket', 'group ticket', 'vip ticket', 'backstage pass', 'guided visit',
      'reservation slot', 'timed entry', 'equipment rental', 'gear rental',
      'bike rental activity', 'kayak rental', 'surfboard rental', 'snorkel gear rental',
      'ski gear rental', 'snowboard rental', 'camping gear rental', 'tent rental',
      'sleeping bag rental', 'hiking pole rental', 'life jacket rental', 'wetsuit rental',
      'dive gear rental', 'fishing gear rental', 'golf club rental', 'tennis racket rental',
      'golf outing', 'tennis court rental', 'bowling activity', 'mini golf', 'go karting',
      'paintball', 'laser tag activity', 'archery lesson', 'fishing charter', 'surf lesson',
      'dive lesson', 'yoga class', 'pilates class', 'gym day pass', 'rock climbing gym',
      'trampoline park', 'climbing wall',
    ],
  ],
  [
    'Entertainment',
    [
      'movie', 'cinema', 'theater', 'theatre', 'club', 'nightclub', 'karaoke', 'arcade',
      'concert', 'show', 'festival', 'entertainment', 'movie theater', 'multiplex', 'imax',
      'drive-in movie', 'art house cinema', 'broadway show', 'west end show', 'opera house',
      'ballet performance', 'symphony', 'orchestra concert', 'jazz club', 'comedy club',
      'stand-up comedy', 'open mic', 'live music venue', 'music festival', 'film festival',
      'art festival', 'cultural festival', 'street festival', 'carnival', 'circus show',
      'magic show', 'puppet show', 'dinner theater', 'dinner cruise show', 'cabaret',
      'burlesque show', 'drag show', 'karaoke bar', 'piano bar', 'pool hall', 'billiards',
      'bowling alley entertainment', 'video game arcade', 'escape room entertainment',
      'laser tag entertainment', 'trampoline park entertainment', 'vr experience',
      'virtual reality arcade', 'board game cafe', 'casino', 'slot machine', 'poker room',
      'blackjack table', 'roulette table', 'bingo hall', 'lottery ticket', 'sports betting',
      'fantasy sports', 'rock concert', 'pop concert', 'hip hop show', 'rap concert',
      'country music show', 'jazz concert', 'classical concert', 'electronic music festival',
      'edm festival', 'reggae show', 'blues club', 'folk music show', 'indie concert',
      'metal concert', 'punk show', 'dj set', 'live band', 'tribute band', 'cover band',
      'movie ticket', 'cinema ticket', 'theater ticket', 'show ticket', 'concert ticket',
      'festival pass', 'festival ticket', 'vip concert ticket', 'backstage concert pass',
      'season tickets sports', 'sports game ticket', 'football game', 'basketball game',
      'baseball game', 'hockey game', 'soccer match', 'tennis match', 'boxing match',
      'wrestling match', 'ufc fight', 'stadium event', 'arena show', 'amphitheater show',
      'outdoor concert', 'rooftop cinema', 'pop up cinema', 'bar crawl', 'pub crawl',
      'happy hour drinks entertainment', 'late night club', 'rooftop club', 'beach club',
      'pool party', 'dance club', 'lounge bar', 'hookah lounge', 'cigar lounge',
      'wine tasting event', 'beer tasting event', 'cocktail masterclass', 'mixology class',
      'action movie', 'comedy movie', 'horror movie', 'romance movie', 'documentary film',
      'animated movie', 'thriller movie', 'drama film', 'musical film', 'sci-fi movie',
      'fantasy movie', 'western film', 'war film', 'crime film', 'mystery movie',
      'superhero movie', 'adventure film', 'biopic film', 'noir film', 'indie film',
      'movie premiere', 'movie screening', 'matinee show',
    ],
  ],
  [
    'Shopping',
    [
      'shopping', 'store', 'mall', 'souvenir', 'clothes', 'clothing', 'shoes', 'gift',
      'boutique', 'market', 'department store', 'outlet mall', 'strip mall', 'shopping mall',
      'shopping center', 'flea market', 'night market', 'street market', 'craft market',
      'antique shop', 'thrift store', 'secondhand store', 'vintage shop', 'consignment shop',
      'pawn shop', 'duty free shop', 'airport shopping', 'gift shop', 'souvenir shop',
      'jewelry store', 'watch store', 'electronics store', 'bookstore', 'toy store',
      'sporting goods store', 'shoe store', 'hat shop', 'accessory store', 'handbag store',
      'luggage store', 'home goods store', 'furniture store', 'hardware store',
      'stationery store', 'art supply store', 'music store', 'record store', 'perfume shop',
      'cosmetics store', 'beauty supply store', 'department store sale', 'outlet shopping',
      'online shopping', 'curbside pickup shopping', 'shirt', 't-shirt', 'blouse', 'dress',
      'skirt', 'pants', 'jeans', 'shorts', 'jacket', 'coat', 'sweater', 'hoodie', 'suit',
      'necktie', 'scarf', 'hat', 'cap', 'gloves', 'socks', 'underwear', 'swimsuit', 'bikini',
      'sandals', 'sneakers', 'boots', 'heels', 'flats', 'belt', 'handbag', 'purse', 'backpack',
      'wallet', 'sunglasses', 'watch accessory', 'jewelry piece', 'necklace', 'bracelet',
      'earrings', 'ring accessory', 'brooch', 'cufflinks', 'umbrella', 'luggage piece',
      'suitcase', 'leather jacket', 'silk scarf', 'wool sweater', 'designer bag', 'luxury watch',
      'cashmere sweater', 'denim jacket', 'zara', 'h&m', 'uniqlo', 'gap store', 'nike store',
      'adidas store', 'levis', 'gucci', 'prada', 'louis vuitton', 'chanel', 'hermes', 'versace',
      'armani', 'burberry', 'ralph lauren', 'tommy hilfiger', 'calvin klein', 'forever 21',
      'topshop', 'primark', 'mango store', 'bershka', 'pull and bear', 'massimo dutti',
      'nordstrom', 'macys', 'bloomingdales', 'target store', 'walmart shopping',
      'costco shopping', 'ikea', 'zara home', 'sephora', 'ulta beauty', 'victoria secret',
      'postcard', 'souvenir magnet', 'keychain', 'snow globe', 'local craft',
      'handmade souvenir', 'local artwork', 'tourist trinket', 'fridge magnet', 'local pottery',
      'local textile', 'local spice souvenir', 'local wine souvenir', 'duty free perfume',
      'duty free alcohol', 'duty free chocolate', 'bargain', 'haggle', 'discount shopping',
      'clearance sale', 'markdown', 'price tag', 'receipt', 'tax refund shopping', 'vat refund',
      'shopping bag', 'shopping spree', 'window shopping', 'try on clothes', 'fitting room',
      'checkout counter', 'cashier',
    ],
  ],
];

function escapeRegExp(text: string): string {
  return text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

// Precompiled once at module load rather than per classify() call, since
// callers may invoke this on every debounced keystroke. Word-boundary (\b)
// matching — rather than plain substring .includes() — avoids false
// positives like "art" matching inside "party" or "gas" matching "gasp".
const CATEGORY_MATCHERS: [Category, RegExp[]][] = CATEGORY_KEYWORDS.map(([category, keywords]) => [
  category,
  keywords.map((keyword) => new RegExp(`\\b${escapeRegExp(keyword)}\\b`, 'i')),
]);

function classify(englishText: string): Category {
  for (const [category, regexes] of CATEGORY_MATCHERS) {
    if (regexes.some((regex) => regex.test(englishText))) return category;
  }
  return 'Other';
}

// Best-effort category guess from a free-text expense description: translate
// to English (the descriptions are entered in the app's UI language) then
// match against a curated keyword list per category. Falls back to 'Other'
// when nothing matches or translation fails outright — this never throws, so
// callers can fire-and-forget it without a try/catch of their own.
export async function guessCategory(description: string): Promise<Category> {
  const trimmed = description.trim();
  if (!trimmed) return 'Other';
  try {
    const english = await translateToEnglish(trimmed);
    return classify(english || trimmed);
  } catch {
    return classify(trimmed);
  }
}
